/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define BOARD_XTAL0_CLK_HZ                         50000000U  /*!< Board xtal0 frequency in Hz */

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ********************* Configuration RTECLK_HsRun_180MHz ***********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for RTECLK_HsRun_180MHz configuration
 ******************************************************************************/
#define RTECLK_HSRUN_180MHZ_CORE_CLOCK            180000000U  /*!< Core clock frequency: 180000000Hz */

/*! @brief MCG set for RTECLK_HsRun_180MHz configuration.
 */
extern const mcg_config_t mcgConfig_RTECLK_HsRun_180MHz;
/*! @brief SIM module set for RTECLK_HsRun_180MHz configuration.
 */
extern const sim_clock_config_t simConfig_RTECLK_HsRun_180MHz;
/*! @brief OSC set for RTECLK_HsRun_180MHz configuration.
 */
extern const osc_config_t oscConfig_RTECLK_HsRun_180MHz;

/*******************************************************************************
 * API for RTECLK_HsRun_180MHz configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void RTECLK_HsRun_180MHz(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ********************* Configuration RTECLK_MsRun_120MHz ***********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for RTECLK_MsRun_120MHz configuration
 ******************************************************************************/
#define RTECLK_MSRUN_120MHZ_CORE_CLOCK            120000000U  /*!< Core clock frequency: 120000000Hz */

/*! @brief MCG set for RTECLK_MsRun_120MHz configuration.
 */
extern const mcg_config_t mcgConfig_RTECLK_MsRun_120MHz;
/*! @brief SIM module set for RTECLK_MsRun_120MHz configuration.
 */
extern const sim_clock_config_t simConfig_RTECLK_MsRun_120MHz;
/*! @brief OSC set for RTECLK_MsRun_120MHz configuration.
 */
extern const osc_config_t oscConfig_RTECLK_MsRun_120MHz;

/*******************************************************************************
 * API for RTECLK_MsRun_120MHz configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void RTECLK_MsRun_120MHz(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ********************* Configuration RTECLK_LpRun_060MHz ***********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for RTECLK_LpRun_060MHz configuration
 ******************************************************************************/
#define RTECLK_LPRUN_060MHZ_CORE_CLOCK             60000000U  /*!< Core clock frequency: 60000000Hz */

/*! @brief MCG set for RTECLK_LpRun_060MHz configuration.
 */
extern const mcg_config_t mcgConfig_RTECLK_LpRun_060MHz;
/*! @brief SIM module set for RTECLK_LpRun_060MHz configuration.
 */
extern const sim_clock_config_t simConfig_RTECLK_LpRun_060MHz;
/*! @brief OSC set for RTECLK_LpRun_060MHz configuration.
 */
extern const osc_config_t oscConfig_RTECLK_LpRun_060MHz;

/*******************************************************************************
 * API for RTECLK_LpRun_060MHz configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void RTECLK_LpRun_060MHz(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

