/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: MK66FX1M0xxx18
package_id: MK66FX1M0VLQ18
mcu_data: ksdk2_0
processor_version: 6.0.1
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_BasicPin:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '5', peripheral: SUPPLY, signal: 'VDD, 0', pin_signal: VDD5}
  - {pin_num: '6', peripheral: SUPPLY, signal: 'VSS, 0', pin_signal: VSS6}
  - {pin_num: '17', peripheral: SUPPLY, signal: 'VSS, 1', pin_signal: VSS17}
  - {pin_num: '18', peripheral: SUPPLY, signal: 'VSS, 2', pin_signal: VSS22}
  - {pin_num: '16', peripheral: SUPPLY, signal: 'VDD, 1', pin_signal: VDD16}
  - {pin_num: '31', peripheral: DAC0, signal: REF_2, pin_signal: VDDA}
  - {pin_num: '31', peripheral: DAC1, signal: REF_2, pin_signal: VDDA}
  - {pin_num: '31', peripheral: SUPPLY, signal: 'VDDA, 0', pin_signal: VDDA}
  - {pin_num: '32', peripheral: ADC0, signal: VREFH, pin_signal: VREFH}
  - {pin_num: '32', peripheral: ADC1, signal: VREFH, pin_signal: VREFH}
  - {pin_num: '33', peripheral: ADC0, signal: VREFL, pin_signal: VREFL}
  - {pin_num: '33', peripheral: ADC1, signal: VREFL, pin_signal: VREFL}
  - {pin_num: '34', peripheral: ADC0, signal: VALTL, pin_signal: VSSA}
  - {pin_num: '34', peripheral: ADC1, signal: VALTL, pin_signal: VSSA}
  - {pin_num: '34', peripheral: SUPPLY, signal: 'VSSA, 0', pin_signal: VSSA}
  - {pin_num: '43', peripheral: SUPPLY, signal: 'VDD, 2', pin_signal: VDD66}
  - {pin_num: '44', peripheral: SUPPLY, signal: 'VSS, 3', pin_signal: VSS67}
  - {pin_num: '42', peripheral: RTC, signal: VBAT, pin_signal: VBAT}
  - {pin_num: '56', peripheral: SUPPLY, signal: 'VDD, 3', pin_signal: VDD80}
  - {pin_num: '57', peripheral: SUPPLY, signal: 'VSS, 4', pin_signal: VSS81}
  - {pin_num: '70', peripheral: SUPPLY, signal: 'VDD, 4', pin_signal: VDD94}
  - {pin_num: '71', peripheral: SUPPLY, signal: 'VSS, 5', pin_signal: VSS95}
  - {pin_num: '74', peripheral: RCM, signal: RESET, pin_signal: RESET_b}
  - {pin_num: '93', peripheral: SUPPLY, signal: 'VSS, 7', pin_signal: VSS125}
  - {pin_num: '94', peripheral: SUPPLY, signal: 'VDD, 6', pin_signal: VDD126}
  - {pin_num: '107', peripheral: SUPPLY, signal: 'VSS, 8', pin_signal: VSS139}
  - {pin_num: '108', peripheral: SUPPLY, signal: 'VDD, 7', pin_signal: VDD140}
  - {pin_num: '121', peripheral: SUPPLY, signal: 'VSS, 9', pin_signal: VSS153}
  - {pin_num: '122', peripheral: SUPPLY, signal: 'VDD, 8', pin_signal: VDD154}
  - {pin_num: '50', peripheral: JTAG, signal: JTAG_TCLK_SWD_CLK, pin_signal: TSI0_CH1/PTA0/UART0_CTS_b/UART0_COL_b/FTM0_CH5/LPUART0_CTS_b/JTAG_TCLK/SWD_CLK/EZP_CLK}
  - {pin_num: '53', peripheral: JTAG, signal: JTAG_TMS_SWD_DIO, pin_signal: TSI0_CH4/PTA3/UART0_RTS_b/FTM0_CH0/LPUART0_RTS_b/JTAG_TMS/SWD_DIO}
  - {pin_num: '55', peripheral: JTAG, signal: TRST, pin_signal: PTA5/USB0_CLKIN/FTM0_CH2/RMII0_RXER/MII0_RXER/CMP2_OUT/I2S0_TX_BCLK/JTAG_TRST_b}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_BasicPin
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_BasicPin(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);

    /* PORTA0 (pin 50) is configured as JTAG_TCLK */
    PORT_SetPinMux(PORTA, 0U, kPORT_MuxAlt7);

    /* PORTA3 (pin 53) is configured as JTAG_TMS */
    PORT_SetPinMux(PORTA, 3U, kPORT_MuxAlt7);

    /* PORTA5 (pin 55) is configured as JTAG_TRST_b */
    PORT_SetPinMux(PORTA, 5U, kPORT_MuxAlt7);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_Uart0_SWO:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '51', peripheral: UART0, signal: RX, pin_signal: TSI0_CH2/PTA1/UART0_RX/FTM0_CH6/I2C3_SDA/LPUART0_RX/JTAG_TDI/EZP_DI}
  - {pin_num: '52', peripheral: UART0, signal: TX, pin_signal: TSI0_CH3/PTA2/UART0_TX/FTM0_CH7/I2C3_SCL/LPUART0_TX/JTAG_TDO/TRACE_SWO/EZP_DO}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_Uart0_SWO
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_Uart0_SWO(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);

    /* PORTA1 (pin 51) is configured as UART0_RX */
    PORT_SetPinMux(PORTA, 1U, kPORT_MuxAlt2);

    /* PORTA2 (pin 52) is configured as UART0_TX */
    PORT_SetPinMux(PORTA, 2U, kPORT_MuxAlt2);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK)))

                  /* UART 0 transmit data source select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
