/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v8.0
processor: MK66FX1M0xxx18
package_id: MK66FX1M0VLQ18
mcu_data: ksdk2_0
processor_version: 8.0.1
pin_labels:
- {pin_num: '60', pin_signal: ADC0_SE11/PTA8/FTM1_CH0/RMII0_MDC/MII0_MDC/FTM1_QD_PHA/TPM1_CH0/TRACE_D2, label: 电磁}
- {pin_num: '59', pin_signal: ADC0_SE10/PTA7/FTM0_CH4/RMII0_MDIO/MII0_MDIO/TRACE_D3, label: 电磁}
- {pin_num: '3', pin_signal: ADC1_SE6a/PTE2/LLWU_P1/SPI1_SCK/UART1_CTS_b/SDHC0_DCLK/TRACE_D2, label: SD_CLK, identifier: SD_CLK}
- {pin_num: '4', pin_signal: ADC1_SE7a/PTE3/SPI1_SIN/UART1_RTS_b/SDHC0_CMD/TRACE_D1/SPI1_SOUT, label: SD_CMD, identifier: SD_CMD}
- {pin_num: '7', pin_signal: PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/SDHC0_D3/TRACE_D0, label: SD_D_3, identifier: SD_D_3}
- {pin_num: '8', pin_signal: PTE5/SPI1_PCS2/UART3_RX/SDHC0_D2/FTM3_CH0, label: SD_D_2, identifier: SD_D_2}
- {pin_num: '2', pin_signal: ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/SDHC0_D0/TRACE_D3/I2C1_SCL/SPI1_SIN, label: SD_D_0, identifier: SD_D_0}
- {pin_num: '1', pin_signal: ADC1_SE4a/PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/TRACE_CLKOUT/I2C1_SDA/RTC_CLKOUT, label: SD_D_1, identifier: SD_D_1}
- {pin_num: '11', pin_signal: PTE8/I2S0_RXD1/I2S0_RX_FS/LPUART0_TX/FTM3_CH3, label: BUTTON_LF, identifier: BUTTON_LF}
- {pin_num: '12', pin_signal: PTE9/LLWU_P17/I2S0_TXD1/I2S0_RX_BCLK/LPUART0_RX/FTM3_CH4, label: BUTTON_RT, identifier: BUTTON_RT}
- {pin_num: '14', pin_signal: PTE11/I2C3_SCL/I2S0_TX_FS/LPUART0_RTS_b/FTM3_CH6, label: BUTTON_DN, identifier: BUTTON_DN}
- {pin_num: '15', pin_signal: PTE12/I2S0_TX_BCLK/FTM3_CH7, label: SERVO_0, identifier: SERVO_0}
- {pin_num: '53', pin_signal: TSI0_CH4/PTA3/UART0_RTS_b/FTM0_CH0/LPUART0_RTS_b/JTAG_TMS/SWD_DIO, label: SWO_DIO, identifier: SWO_DIO}
- {pin_num: '50', pin_signal: TSI0_CH1/PTA0/UART0_CTS_b/UART0_COL_b/FTM0_CH5/LPUART0_CTS_b/JTAG_TCLK/SWD_CLK/EZP_CLK, label: SWO_CLK, identifier: SWO_CLK}
- {pin_num: '51', pin_signal: TSI0_CH2/PTA1/UART0_RX/FTM0_CH6/I2C3_SDA/LPUART0_RX/JTAG_TDI/EZP_DI, label: UART_DBG_RX, identifier: UART_DBG_RX}
- {pin_num: '52', pin_signal: TSI0_CH3/PTA2/UART0_TX/FTM0_CH7/I2C3_SCL/LPUART0_TX/JTAG_TDO/TRACE_SWO/EZP_DO, label: UART_DBG_TX, identifier: UART_DBG_TX}
- {pin_num: '61', pin_signal: PTA9/FTM1_CH1/MII0_RXD3/FTM1_QD_PHB/TPM1_CH1/TRACE_D1, label: SWITCH_0, identifier: SWITCH_0}
- {pin_num: '63', pin_signal: PTA11/LLWU_P23/FTM2_CH1/MII0_RXCLK/I2C2_SDA/FTM2_QD_PHB/TPM2_CH1, label: SWITCH_1, identifier: SWITCH_1}
- {pin_num: '67', pin_signal: CMP3_IN1/PTA15/SPI0_SCK/UART0_RX/RMII0_TXEN/MII0_TXEN/I2S0_RXD0, label: SWITCH_3, identifier: SWITCH_3}
- {pin_num: '65', pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/RMII0_RXD0/MII0_RXD0/I2C2_SDA/I2S0_TX_FS/FTM1_QD_PHB/TPM1_CH1, label: SWITCH_2, identifier: SWITCH_2}
- {pin_num: '81', pin_signal: ADC0_SE8/ADC1_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/SDRAM_CAS_b/FTM1_QD_PHA/TPM1_CH0, label: ENCO_LA, identifier: ENCO_LA}
- {pin_num: '82', pin_signal: ADC0_SE9/ADC1_SE9/TSI0_CH6/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/SDRAM_RAS_b/FTM1_QD_PHB/TPM1_CH1, label: ENCO_LB, identifier: ENCO_LB}
- {pin_num: '97', pin_signal: TSI0_CH11/PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/SDRAM_A23/FTM2_QD_PHA/TPM2_CH0, label: ENCO_RA, identifier: ENCO_RA}
- {pin_num: '98', pin_signal: TSI0_CH12/PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB/TPM2_CH1, label: ENCO_RB, identifier: ENCO_RB}
- {pin_num: '111', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/I2S0_RX_BCLK/FB_AD9/SDRAM_A17/I2S0_MCLK, label: CAM_VSNC, identifier: CAM_VSNC}
- {pin_num: '113', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7/SDRAM_A15, label: CAM_D_0, identifier: CAM_D_0}
- {pin_num: '125', pin_signal: PTC18/UART3_RTS_b/ENET0_1588_TMR2/FB_TBST_b/FB_CS2_b/FB_BE15_8_BLS23_16_b/SDRAM_DQM1, label: CAM_PCLK, identifier: CAM_PCLK}
- {pin_num: '114', pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/I2S0_RX_BCLK/FB_AD6/SDRAM_A14/FTM2_FLT0, label: CAM_D_1, identifier: CAM_D_1}
- {pin_num: '115', pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5/SDRAM_A13, label: CAM_D_2, identifier: CAM_D_2}
- {pin_num: '116', pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/I2S0_RXD1/FB_RW_b, label: CAM_D_3, identifier: CAM_D_3}
- {pin_num: '117', pin_signal: PTC12/UART4_RTS_b/FTM_CLKIN0/FB_AD27/SDRAM_D27/FTM3_FLT0/TPM_CLKIN0, label: CAM_D_4, identifier: CAM_D_4}
- {pin_num: '118', pin_signal: PTC13/UART4_CTS_b/FTM_CLKIN1/FB_AD26/SDRAM_D26/TPM_CLKIN1, label: CAM_D_5, identifier: CAM_D_5}
- {pin_num: '119', pin_signal: PTC14/UART4_RX/FB_AD25/SDRAM_D25, label: CAM_D_6, identifier: CAM_D_6}
- {pin_num: '120', pin_signal: PTC15/UART4_TX/FB_AD24/SDRAM_D24, label: CAM_D_7, identifier: CAM_D_7}
- {pin_num: '133', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FB_AD0/FTM0_FLT0/SPI1_SOUT, label: UART_WLAN_RX, identifier: UART_WLAN_RX}
- {pin_num: '136', pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/SDRAM_CKE/FTM0_FLT1/SPI1_SIN, label: UART_WLAN_TX, identifier: UART_WLAN_TX}
- {pin_num: '137', pin_signal: PTD8/LLWU_P24/I2C0_SCL/LPUART0_RX/FB_A16, label: IMU_SCL, identifier: IMU_SCL}
- {pin_num: '138', pin_signal: PTD9/I2C0_SDA/LPUART0_TX/FB_A17, label: IMU_SDA, identifier: IMU_SDA}
- {pin_num: '104', pin_signal: ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/SDRAM_A21/I2S0_TXD0, label: MOTOR_RA, identifier: MOTOR_RA}
- {pin_num: '105', pin_signal: ADC0_SE4b/CMP1_IN0/TSI0_CH15/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FB_AD12/SDRAM_A20/I2S0_TX_FS, label: MOTOR_RB, identifier: MOTOR_RB}
- {pin_num: '106', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK, label: MOTOR_LA, identifier: MOTOR_LA}
- {pin_num: '109', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/SDRAM_A19/CMP1_OUT, label: MOTOR_LB, identifier: MOTOR_LB}
- {pin_num: '55', pin_signal: PTA5/USB0_CLKIN/FTM0_CH2/RMII0_RXER/MII0_RXER/CMP2_OUT/I2S0_TX_BCLK/JTAG_TRST_b, label: RST, identifier: RST}
- {pin_num: '13', pin_signal: PTE10/LLWU_P18/I2C3_SDA/I2S0_TXD0/LPUART0_CTS_b/FTM3_CH5/USB1_ID, label: BUTTON_OK, identifier: BUTTON_OK}
- {pin_num: '10', pin_signal: PTE7/UART3_RTS_b/I2S0_RXD0/FTM3_CH2, label: BUTTON_UP, identifier: BUTTON_UP}
- {pin_num: '100', pin_signal: PTB21/SPI2_SCK/FB_AD30/SDRAM_D30/CMP1_OUT, label: OLED_D_C, identifier: OLED_D_C}
- {pin_num: '99', pin_signal: PTB20/SPI2_PCS0/FB_AD31/SDRAM_D31/CMP0_OUT, label: OLED_RST, identifier: OLED_RST}
- {pin_num: '101', pin_signal: PTB22/SPI2_SOUT/FB_AD29/SDRAM_D29/CMP2_OUT, label: OLED_SCK, identifier: OLED_SCK}
- {pin_num: '102', pin_signal: PTB23/SPI2_SIN/SPI0_PCS5/FB_AD28/SDRAM_D28/CMP3_OUT, label: OLED_SOT, identifier: OLED_SOT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_Basic:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '111', peripheral: GPIOC, signal: 'GPIO, 6', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/I2S0_RX_BCLK/FB_AD9/SDRAM_A17/I2S0_MCLK}
  - {pin_num: '113', peripheral: GPIOC, signal: 'GPIO, 8', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7/SDRAM_A15}
  - {pin_num: '114', peripheral: GPIOC, signal: 'GPIO, 9', pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/I2S0_RX_BCLK/FB_AD6/SDRAM_A14/FTM2_FLT0}
  - {pin_num: '115', peripheral: GPIOC, signal: 'GPIO, 10', pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5/SDRAM_A13}
  - {pin_num: '116', peripheral: GPIOC, signal: 'GPIO, 11', pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/I2S0_RXD1/FB_RW_b}
  - {pin_num: '119', peripheral: GPIOC, signal: 'GPIO, 14', pin_signal: PTC14/UART4_RX/FB_AD25/SDRAM_D25}
  - {pin_num: '118', peripheral: GPIOC, signal: 'GPIO, 13', pin_signal: PTC13/UART4_CTS_b/FTM_CLKIN1/FB_AD26/SDRAM_D26/TPM_CLKIN1}
  - {pin_num: '117', peripheral: GPIOC, signal: 'GPIO, 12', pin_signal: PTC12/UART4_RTS_b/FTM_CLKIN0/FB_AD27/SDRAM_D27/FTM3_FLT0/TPM_CLKIN0}
  - {pin_num: '120', peripheral: GPIOC, signal: 'GPIO, 15', pin_signal: PTC15/UART4_TX/FB_AD24/SDRAM_D24}
  - {pin_num: '125', peripheral: GPIOC, signal: 'GPIO, 18', pin_signal: PTC18/UART3_RTS_b/ENET0_1588_TMR2/FB_TBST_b/FB_CS2_b/FB_BE15_8_BLS23_16_b/SDRAM_DQM1}
  - {pin_num: '7', peripheral: GPIOE, signal: 'GPIO, 4', pin_signal: PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/SDHC0_D3/TRACE_D0}
  - {pin_num: '8', peripheral: GPIOE, signal: 'GPIO, 5', pin_signal: PTE5/SPI1_PCS2/UART3_RX/SDHC0_D2/FTM3_CH0}
  - {pin_num: '50', peripheral: JTAG, signal: JTAG_TCLK_SWD_CLK, pin_signal: TSI0_CH1/PTA0/UART0_CTS_b/UART0_COL_b/FTM0_CH5/LPUART0_CTS_b/JTAG_TCLK/SWD_CLK/EZP_CLK}
  - {pin_num: '53', peripheral: JTAG, signal: JTAG_TMS_SWD_DIO, pin_signal: TSI0_CH4/PTA3/UART0_RTS_b/FTM0_CH0/LPUART0_RTS_b/JTAG_TMS/SWD_DIO}
  - {pin_num: '55', peripheral: JTAG, signal: TRST, pin_signal: PTA5/USB0_CLKIN/FTM0_CH2/RMII0_RXER/MII0_RXER/CMP2_OUT/I2S0_TX_BCLK/JTAG_TRST_b}
  - {pin_num: '123', peripheral: UART3, signal: RX, pin_signal: PTC16/CAN1_RX/UART3_RX/ENET0_1588_TMR0/FB_CS5_b/FB_TSIZ1/FB_BE23_16_BLS15_8_b/SDRAM_DQM2}
  - {pin_num: '124', peripheral: UART3, signal: TX, pin_signal: PTC17/CAN1_TX/UART3_TX/ENET0_1588_TMR1/FB_CS4_b/FB_TSIZ0/FB_BE31_24_BLS7_0_b/SDRAM_DQM3}
  - {pin_num: '137', peripheral: I2C0, signal: SCL, pin_signal: PTD8/LLWU_P24/I2C0_SCL/LPUART0_RX/FB_A16, open_drain: enable, pull_select: up, pull_enable: enable}
  - {pin_num: '138', peripheral: I2C0, signal: SDA, pin_signal: PTD9/I2C0_SDA/LPUART0_TX/FB_A17, open_drain: enable, pull_select: up, pull_enable: enable}
  - {pin_num: '9', peripheral: GPIOE, signal: 'GPIO, 6', pin_signal: PTE6/LLWU_P16/SPI1_PCS3/UART3_CTS_b/I2S0_MCLK/FTM3_CH1/USB0_SOF_OUT}
  - {pin_num: '10', peripheral: GPIOE, signal: 'GPIO, 7', pin_signal: PTE7/UART3_RTS_b/I2S0_RXD0/FTM3_CH2, pull_select: up, pull_enable: enable}
  - {pin_num: '11', peripheral: GPIOE, signal: 'GPIO, 8', pin_signal: PTE8/I2S0_RXD1/I2S0_RX_FS/LPUART0_TX/FTM3_CH3, pull_select: up, pull_enable: enable}
  - {pin_num: '12', peripheral: GPIOE, signal: 'GPIO, 9', pin_signal: PTE9/LLWU_P17/I2S0_TXD1/I2S0_RX_BCLK/LPUART0_RX/FTM3_CH4, pull_select: up, pull_enable: enable}
  - {pin_num: '13', peripheral: GPIOE, signal: 'GPIO, 10', pin_signal: PTE10/LLWU_P18/I2C3_SDA/I2S0_TXD0/LPUART0_CTS_b/FTM3_CH5/USB1_ID, pull_select: up, pull_enable: enable}
  - {pin_num: '14', peripheral: GPIOE, signal: 'GPIO, 11', pin_signal: PTE11/I2C3_SCL/I2S0_TX_FS/LPUART0_RTS_b/FTM3_CH6, pull_select: up, pull_enable: enable}
  - {pin_num: '61', peripheral: GPIOA, signal: 'GPIO, 9', pin_signal: PTA9/FTM1_CH1/MII0_RXD3/FTM1_QD_PHB/TPM1_CH1/TRACE_D1}
  - {pin_num: '63', peripheral: GPIOA, signal: 'GPIO, 11', pin_signal: PTA11/LLWU_P23/FTM2_CH1/MII0_RXCLK/I2C2_SDA/FTM2_QD_PHB/TPM2_CH1}
  - {pin_num: '65', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/RMII0_RXD0/MII0_RXD0/I2C2_SDA/I2S0_TX_FS/FTM1_QD_PHB/TPM1_CH1}
  - {pin_num: '67', peripheral: GPIOA, signal: 'GPIO, 15', pin_signal: CMP3_IN1/PTA15/SPI0_SCK/UART0_RX/RMII0_TXEN/MII0_TXEN/I2S0_RXD0}
  - {pin_num: '45', peripheral: ADC0, signal: 'SE, 17', pin_signal: ADC0_SE17/PTE24/CAN1_TX/UART4_TX/I2C0_SCL/EWM_OUT_b}
  - {pin_num: '46', peripheral: ADC0, signal: 'SE, 18', pin_signal: ADC0_SE18/PTE25/LLWU_P21/CAN1_RX/UART4_RX/I2C0_SDA/EWM_IN}
  - {pin_num: '59', peripheral: ADC0, signal: 'SE, 10', pin_signal: ADC0_SE10/PTA7/FTM0_CH4/RMII0_MDIO/MII0_MDIO/TRACE_D3}
  - {pin_num: '60', peripheral: ADC0, signal: 'SE, 11', pin_signal: ADC0_SE11/PTA8/FTM1_CH0/RMII0_MDC/MII0_MDC/FTM1_QD_PHA/TPM1_CH0/TRACE_D2}
  - {pin_num: '36', peripheral: ADC0, signal: 'SE, 16', pin_signal: ADC0_SE16/CMP1_IN2/ADC0_SE21}
  - {pin_num: '38', peripheral: ADC0, signal: 'SE, 23', pin_signal: DAC0_OUT/CMP1_IN3/ADC0_SE23}
  - {pin_num: '81', peripheral: FTM1, signal: 'QD_PH, A', pin_signal: ADC0_SE8/ADC1_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/SDRAM_CAS_b/FTM1_QD_PHA/TPM1_CH0}
  - {pin_num: '82', peripheral: FTM1, signal: 'QD_PH, B', pin_signal: ADC0_SE9/ADC1_SE9/TSI0_CH6/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/SDRAM_RAS_b/FTM1_QD_PHB/TPM1_CH1}
  - {pin_num: '97', peripheral: FTM2, signal: 'QD_PH, A', pin_signal: TSI0_CH11/PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/SDRAM_A23/FTM2_QD_PHA/TPM2_CH0}
  - {pin_num: '98', peripheral: FTM2, signal: 'QD_PH, B', pin_signal: TSI0_CH12/PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB/TPM2_CH1}
  - {pin_num: '15', peripheral: FTM3, signal: 'CH, 7', pin_signal: PTE12/I2S0_TX_BCLK/FTM3_CH7}
  - {pin_num: '1', peripheral: SDHC, signal: 'DATA, 1', pin_signal: ADC1_SE4a/PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/TRACE_CLKOUT/I2C1_SDA/RTC_CLKOUT}
  - {pin_num: '2', peripheral: SDHC, signal: 'DATA, 0', pin_signal: ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/SDHC0_D0/TRACE_D3/I2C1_SCL/SPI1_SIN}
  - {pin_num: '3', peripheral: SDHC, signal: DCLK, pin_signal: ADC1_SE6a/PTE2/LLWU_P1/SPI1_SCK/UART1_CTS_b/SDHC0_DCLK/TRACE_D2}
  - {pin_num: '4', peripheral: SDHC, signal: CMD, pin_signal: ADC1_SE7a/PTE3/SPI1_SIN/UART1_RTS_b/SDHC0_CMD/TRACE_D1/SPI1_SOUT}
  - {pin_num: '5', peripheral: SUPPLY, signal: 'VDD, 0', pin_signal: VDD5}
  - {pin_num: '16', peripheral: SUPPLY, signal: 'VDD, 1', pin_signal: VDD16}
  - {pin_num: '43', peripheral: SUPPLY, signal: 'VDD, 2', pin_signal: VDD66}
  - {pin_num: '56', peripheral: SUPPLY, signal: 'VDD, 3', pin_signal: VDD80}
  - {pin_num: '70', peripheral: SUPPLY, signal: 'VDD, 4', pin_signal: VDD94}
  - {pin_num: '94', peripheral: SUPPLY, signal: 'VDD, 6', pin_signal: VDD126}
  - {pin_num: '108', peripheral: SUPPLY, signal: 'VDD, 7', pin_signal: VDD140}
  - {pin_num: '122', peripheral: SUPPLY, signal: 'VDD, 8', pin_signal: VDD154}
  - {pin_num: '31', peripheral: SUPPLY, signal: 'VDDA, 0', pin_signal: VDDA}
  - {pin_num: '6', peripheral: SUPPLY, signal: 'VSS, 0', pin_signal: VSS6}
  - {pin_num: '17', peripheral: SUPPLY, signal: 'VSS, 1', pin_signal: VSS17}
  - {pin_num: '18', peripheral: SUPPLY, signal: 'VSS, 2', pin_signal: VSS22}
  - {pin_num: '44', peripheral: SUPPLY, signal: 'VSS, 3', pin_signal: VSS67}
  - {pin_num: '57', peripheral: SUPPLY, signal: 'VSS, 4', pin_signal: VSS81}
  - {pin_num: '71', peripheral: SUPPLY, signal: 'VSS, 5', pin_signal: VSS95}
  - {pin_num: '93', peripheral: SUPPLY, signal: 'VSS, 7', pin_signal: VSS125}
  - {pin_num: '107', peripheral: SUPPLY, signal: 'VSS, 8', pin_signal: VSS139}
  - {pin_num: '121', peripheral: SUPPLY, signal: 'VSS, 9', pin_signal: VSS153}
  - {pin_num: '34', peripheral: SUPPLY, signal: 'VSSA, 0', pin_signal: VSSA}
  - {pin_num: '72', peripheral: OSC, signal: EXTAL0, pin_signal: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0/TPM_CLKIN0}
  - {pin_num: '104', peripheral: FTM0, signal: 'CH, 0', pin_signal: ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/SDRAM_A21/I2S0_TXD0}
  - {pin_num: '105', peripheral: FTM0, signal: 'CH, 1', pin_signal: ADC0_SE4b/CMP1_IN0/TSI0_CH15/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FB_AD12/SDRAM_A20/I2S0_TX_FS}
  - {pin_num: '106', peripheral: FTM0, signal: 'CH, 2', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK}
  - {pin_num: '109', peripheral: FTM0, signal: 'CH, 3', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/SDRAM_A19/CMP1_OUT}
  - {pin_num: '100', peripheral: GPIOB, signal: 'GPIO, 21', pin_signal: PTB21/SPI2_SCK/FB_AD30/SDRAM_D30/CMP1_OUT, direction: OUTPUT, pull_select: up}
  - {pin_num: '99', peripheral: GPIOB, signal: 'GPIO, 20', pin_signal: PTB20/SPI2_PCS0/FB_AD31/SDRAM_D31/CMP0_OUT, direction: OUTPUT, pull_select: up}
  - {pin_num: '101', peripheral: GPIOB, signal: 'GPIO, 22', pin_signal: PTB22/SPI2_SOUT/FB_AD29/SDRAM_D29/CMP2_OUT, direction: OUTPUT, pull_select: up}
  - {pin_num: '102', peripheral: GPIOB, signal: 'GPIO, 23', pin_signal: PTB23/SPI2_SIN/SPI0_PCS5/FB_AD28/SDRAM_D28/CMP3_OUT, direction: OUTPUT, pull_select: up}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_Basic
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_Basic(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t OLED_RST_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB20 (pin 99)  */
    GPIO_PinInit(RTEPIN_BASIC_OLED_RST_GPIO, RTEPIN_BASIC_OLED_RST_PIN, &OLED_RST_config);

    gpio_pin_config_t OLED_D_C_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB21 (pin 100)  */
    GPIO_PinInit(RTEPIN_BASIC_OLED_D_C_GPIO, RTEPIN_BASIC_OLED_D_C_PIN, &OLED_D_C_config);

    gpio_pin_config_t OLED_SCK_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB22 (pin 101)  */
    GPIO_PinInit(RTEPIN_BASIC_OLED_SCK_GPIO, RTEPIN_BASIC_OLED_SCK_PIN, &OLED_SCK_config);

    gpio_pin_config_t OLED_SOT_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB23 (pin 102)  */
    GPIO_PinInit(RTEPIN_BASIC_OLED_SOT_GPIO, RTEPIN_BASIC_OLED_SOT_PIN, &OLED_SOT_config);

    /* PORTA0 (pin 50) is configured as JTAG_TCLK */
    PORT_SetPinMux(RTEPIN_BASIC_SWO_CLK_PORT, RTEPIN_BASIC_SWO_CLK_PIN, kPORT_MuxAlt7);

    /* PORTA11 (pin 63) is configured as PTA11 */
    PORT_SetPinMux(RTEPIN_BASIC_SWITCH_1_PORT, RTEPIN_BASIC_SWITCH_1_PIN, kPORT_MuxAsGpio);

    /* PORTA13 (pin 65) is configured as PTA13 */
    PORT_SetPinMux(RTEPIN_BASIC_SWITCH_2_PORT, RTEPIN_BASIC_SWITCH_2_PIN, kPORT_MuxAsGpio);

    /* PORTA15 (pin 67) is configured as PTA15 */
    PORT_SetPinMux(RTEPIN_BASIC_SWITCH_3_PORT, RTEPIN_BASIC_SWITCH_3_PIN, kPORT_MuxAsGpio);

    /* PORTA18 (pin 72) is configured as EXTAL0 */
    PORT_SetPinMux(PORTA, 18U, kPORT_PinDisabledOrAnalog);

    /* PORTA3 (pin 53) is configured as JTAG_TMS */
    PORT_SetPinMux(RTEPIN_BASIC_SWO_DIO_PORT, RTEPIN_BASIC_SWO_DIO_PIN, kPORT_MuxAlt7);

    /* PORTA5 (pin 55) is configured as JTAG_TRST_b */
    PORT_SetPinMux(RTEPIN_BASIC_RST_PORT, RTEPIN_BASIC_RST_PIN, kPORT_MuxAlt7);

    /* PORTA7 (pin 59) is configured as ADC0_SE10 */
    PORT_SetPinMux(PORTA, 7U, kPORT_PinDisabledOrAnalog);

    /* PORTA8 (pin 60) is configured as ADC0_SE11 */
    PORT_SetPinMux(PORTA, 8U, kPORT_PinDisabledOrAnalog);

    /* PORTA9 (pin 61) is configured as PTA9 */
    PORT_SetPinMux(RTEPIN_BASIC_SWITCH_0_PORT, RTEPIN_BASIC_SWITCH_0_PIN, kPORT_MuxAsGpio);

    /* PORTB0 (pin 81) is configured as FTM1_QD_PHA */
    PORT_SetPinMux(RTEPIN_BASIC_ENCO_LA_PORT, RTEPIN_BASIC_ENCO_LA_PIN, kPORT_MuxAlt6);

    /* PORTB1 (pin 82) is configured as FTM1_QD_PHB */
    PORT_SetPinMux(RTEPIN_BASIC_ENCO_LB_PORT, RTEPIN_BASIC_ENCO_LB_PIN, kPORT_MuxAlt6);

    /* PORTB18 (pin 97) is configured as FTM2_QD_PHA */
    PORT_SetPinMux(RTEPIN_BASIC_ENCO_RA_PORT, RTEPIN_BASIC_ENCO_RA_PIN, kPORT_MuxAlt6);

    /* PORTB19 (pin 98) is configured as FTM2_QD_PHB */
    PORT_SetPinMux(RTEPIN_BASIC_ENCO_RB_PORT, RTEPIN_BASIC_ENCO_RB_PIN, kPORT_MuxAlt6);

    /* PORTB20 (pin 99) is configured as PTB20 */
    PORT_SetPinMux(RTEPIN_BASIC_OLED_RST_PORT, RTEPIN_BASIC_OLED_RST_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[20] = ((PORTB->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB21 (pin 100) is configured as PTB21 */
    PORT_SetPinMux(RTEPIN_BASIC_OLED_D_C_PORT, RTEPIN_BASIC_OLED_D_C_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[21] = ((PORTB->PCR[21] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB22 (pin 101) is configured as PTB22 */
    PORT_SetPinMux(RTEPIN_BASIC_OLED_SCK_PORT, RTEPIN_BASIC_OLED_SCK_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[22] = ((PORTB->PCR[22] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTB23 (pin 102) is configured as PTB23 */
    PORT_SetPinMux(RTEPIN_BASIC_OLED_SOT_PORT, RTEPIN_BASIC_OLED_SOT_PIN, kPORT_MuxAsGpio);

    PORTB->PCR[23] = ((PORTB->PCR[23] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(kPORT_PullUp));

    /* PORTC1 (pin 104) is configured as FTM0_CH0 */
    PORT_SetPinMux(RTEPIN_BASIC_MOTOR_RA_PORT, RTEPIN_BASIC_MOTOR_RA_PIN, kPORT_MuxAlt4);

    /* PORTC10 (pin 115) is configured as PTC10 */
    PORT_SetPinMux(RTEPIN_BASIC_CAM_D_2_PORT, RTEPIN_BASIC_CAM_D_2_PIN, kPORT_MuxAsGpio);

    /* PORTC11 (pin 116) is configured as PTC11 */
    PORT_SetPinMux(RTEPIN_BASIC_CAM_D_3_PORT, RTEPIN_BASIC_CAM_D_3_PIN, kPORT_MuxAsGpio);

    /* PORTC12 (pin 117) is configured as PTC12 */
    PORT_SetPinMux(RTEPIN_BASIC_CAM_D_4_PORT, RTEPIN_BASIC_CAM_D_4_PIN, kPORT_MuxAsGpio);

    /* PORTC13 (pin 118) is configured as PTC13 */
    PORT_SetPinMux(RTEPIN_BASIC_CAM_D_5_PORT, RTEPIN_BASIC_CAM_D_5_PIN, kPORT_MuxAsGpio);

    /* PORTC14 (pin 119) is configured as PTC14 */
    PORT_SetPinMux(RTEPIN_BASIC_CAM_D_6_PORT, RTEPIN_BASIC_CAM_D_6_PIN, kPORT_MuxAsGpio);

    /* PORTC15 (pin 120) is configured as PTC15 */
    PORT_SetPinMux(RTEPIN_BASIC_CAM_D_7_PORT, RTEPIN_BASIC_CAM_D_7_PIN, kPORT_MuxAsGpio);

    /* PORTC16 (pin 123) is configured as UART3_RX */
    PORT_SetPinMux(PORTC, 16U, kPORT_MuxAlt3);

    /* PORTC17 (pin 124) is configured as UART3_TX */
    PORT_SetPinMux(PORTC, 17U, kPORT_MuxAlt3);

    /* PORTC18 (pin 125) is configured as PTC18 */
    PORT_SetPinMux(RTEPIN_BASIC_CAM_PCLK_PORT, RTEPIN_BASIC_CAM_PCLK_PIN, kPORT_MuxAsGpio);

    /* PORTC2 (pin 105) is configured as FTM0_CH1 */
    PORT_SetPinMux(RTEPIN_BASIC_MOTOR_RB_PORT, RTEPIN_BASIC_MOTOR_RB_PIN, kPORT_MuxAlt4);

    /* PORTC3 (pin 106) is configured as FTM0_CH2 */
    PORT_SetPinMux(RTEPIN_BASIC_MOTOR_LA_PORT, RTEPIN_BASIC_MOTOR_LA_PIN, kPORT_MuxAlt4);

    /* PORTC4 (pin 109) is configured as FTM0_CH3 */
    PORT_SetPinMux(RTEPIN_BASIC_MOTOR_LB_PORT, RTEPIN_BASIC_MOTOR_LB_PIN, kPORT_MuxAlt4);

    /* PORTC6 (pin 111) is configured as PTC6 */
    PORT_SetPinMux(RTEPIN_BASIC_CAM_VSNC_PORT, RTEPIN_BASIC_CAM_VSNC_PIN, kPORT_MuxAsGpio);

    /* PORTC8 (pin 113) is configured as PTC8 */
    PORT_SetPinMux(RTEPIN_BASIC_CAM_D_0_PORT, RTEPIN_BASIC_CAM_D_0_PIN, kPORT_MuxAsGpio);

    /* PORTC9 (pin 114) is configured as PTC9 */
    PORT_SetPinMux(RTEPIN_BASIC_CAM_D_1_PORT, RTEPIN_BASIC_CAM_D_1_PIN, kPORT_MuxAsGpio);

    /* PORTD8 (pin 137) is configured as I2C0_SCL */
    PORT_SetPinMux(RTEPIN_BASIC_IMU_SCL_PORT, RTEPIN_BASIC_IMU_SCL_PIN, kPORT_MuxAlt2);

    PORTD->PCR[8] = ((PORTD->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp)

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTD9 (pin 138) is configured as I2C0_SDA */
    PORT_SetPinMux(RTEPIN_BASIC_IMU_SDA_PORT, RTEPIN_BASIC_IMU_SDA_PIN, kPORT_MuxAlt2);

    PORTD->PCR[9] = ((PORTD->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp)

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTE0 (pin 1) is configured as SDHC0_D1 */
    PORT_SetPinMux(RTEPIN_BASIC_SD_D_1_PORT, RTEPIN_BASIC_SD_D_1_PIN, kPORT_MuxAlt4);

    /* PORTE1 (pin 2) is configured as SDHC0_D0 */
    PORT_SetPinMux(RTEPIN_BASIC_SD_D_0_PORT, RTEPIN_BASIC_SD_D_0_PIN, kPORT_MuxAlt4);

    /* PORTE10 (pin 13) is configured as PTE10 */
    PORT_SetPinMux(RTEPIN_BASIC_BUTTON_OK_PORT, RTEPIN_BASIC_BUTTON_OK_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[10] = ((PORTE->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTE11 (pin 14) is configured as PTE11 */
    PORT_SetPinMux(RTEPIN_BASIC_BUTTON_DN_PORT, RTEPIN_BASIC_BUTTON_DN_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[11] = ((PORTE->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTE12 (pin 15) is configured as FTM3_CH7 */
    PORT_SetPinMux(RTEPIN_BASIC_SERVO_0_PORT, RTEPIN_BASIC_SERVO_0_PIN, kPORT_MuxAlt6);

    /* PORTE2 (pin 3) is configured as SDHC0_DCLK */
    PORT_SetPinMux(RTEPIN_BASIC_SD_CLK_PORT, RTEPIN_BASIC_SD_CLK_PIN, kPORT_MuxAlt4);

    /* PORTE24 (pin 45) is configured as ADC0_SE17 */
    PORT_SetPinMux(PORTE, 24U, kPORT_PinDisabledOrAnalog);

    /* PORTE25 (pin 46) is configured as ADC0_SE18 */
    PORT_SetPinMux(PORTE, 25U, kPORT_PinDisabledOrAnalog);

    /* PORTE3 (pin 4) is configured as SDHC0_CMD */
    PORT_SetPinMux(RTEPIN_BASIC_SD_CMD_PORT, RTEPIN_BASIC_SD_CMD_PIN, kPORT_MuxAlt4);

    /* PORTE4 (pin 7) is configured as PTE4 */
    PORT_SetPinMux(RTEPIN_BASIC_SD_D_3_PORT, RTEPIN_BASIC_SD_D_3_PIN, kPORT_MuxAsGpio);

    /* PORTE5 (pin 8) is configured as PTE5 */
    PORT_SetPinMux(RTEPIN_BASIC_SD_D_2_PORT, RTEPIN_BASIC_SD_D_2_PIN, kPORT_MuxAsGpio);

    /* PORTE6 (pin 9) is configured as PTE6 */
    PORT_SetPinMux(PORTE, 6U, kPORT_MuxAsGpio);

    /* PORTE7 (pin 10) is configured as PTE7 */
    PORT_SetPinMux(RTEPIN_BASIC_BUTTON_UP_PORT, RTEPIN_BASIC_BUTTON_UP_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[7] = ((PORTE->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE8 (pin 11) is configured as PTE8 */
    PORT_SetPinMux(RTEPIN_BASIC_BUTTON_LF_PORT, RTEPIN_BASIC_BUTTON_LF_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[8] = ((PORTE->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTE9 (pin 12) is configured as PTE9 */
    PORT_SetPinMux(RTEPIN_BASIC_BUTTON_RT_PORT, RTEPIN_BASIC_BUTTON_RT_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[9] = ((PORTE->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_Digital:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '1', peripheral: SDHC, signal: 'DATA, 1', pin_signal: ADC1_SE4a/PTE0/SPI1_PCS1/UART1_TX/SDHC0_D1/TRACE_CLKOUT/I2C1_SDA/RTC_CLKOUT}
  - {pin_num: '2', peripheral: SDHC, signal: 'DATA, 0', pin_signal: ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/SDHC0_D0/TRACE_D3/I2C1_SCL/SPI1_SIN}
  - {pin_num: '3', peripheral: SDHC, signal: DCLK, pin_signal: ADC1_SE6a/PTE2/LLWU_P1/SPI1_SCK/UART1_CTS_b/SDHC0_DCLK/TRACE_D2}
  - {pin_num: '4', peripheral: SDHC, signal: CMD, pin_signal: ADC1_SE7a/PTE3/SPI1_SIN/UART1_RTS_b/SDHC0_CMD/TRACE_D1/SPI1_SOUT}
  - {pin_num: '8', peripheral: SDHC, signal: 'DATA, 2', pin_signal: PTE5/SPI1_PCS2/UART3_RX/SDHC0_D2/FTM3_CH0}
  - {pin_num: '7', peripheral: SDHC, signal: 'DATA, 3', pin_signal: PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/SDHC0_D3/TRACE_D0}
  - {pin_num: '10', peripheral: GPIOE, signal: 'GPIO, 7', pin_signal: PTE7/UART3_RTS_b/I2S0_RXD0/FTM3_CH2, open_drain: enable, pull_select: up, pull_enable: enable}
  - {pin_num: '11', peripheral: GPIOE, signal: 'GPIO, 8', pin_signal: PTE8/I2S0_RXD1/I2S0_RX_FS/LPUART0_TX/FTM3_CH3, open_drain: enable, pull_select: up, pull_enable: enable}
  - {pin_num: '12', peripheral: GPIOE, signal: 'GPIO, 9', pin_signal: PTE9/LLWU_P17/I2S0_TXD1/I2S0_RX_BCLK/LPUART0_RX/FTM3_CH4, open_drain: enable, pull_select: up,
    pull_enable: enable}
  - {pin_num: '13', peripheral: GPIOE, signal: 'GPIO, 10', pin_signal: PTE10/LLWU_P18/I2C3_SDA/I2S0_TXD0/LPUART0_CTS_b/FTM3_CH5/USB1_ID, open_drain: enable, pull_select: up,
    pull_enable: enable}
  - {pin_num: '14', peripheral: GPIOE, signal: 'GPIO, 11', pin_signal: PTE11/I2C3_SCL/I2S0_TX_FS/LPUART0_RTS_b/FTM3_CH6, open_drain: enable, pull_select: up, pull_enable: enable}
  - {pin_num: '15', peripheral: FTM3, signal: 'CH, 7', pin_signal: PTE12/I2S0_TX_BCLK/FTM3_CH7}
  - {pin_num: '50', peripheral: JTAG, signal: JTAG_TCLK_SWD_CLK, pin_signal: TSI0_CH1/PTA0/UART0_CTS_b/UART0_COL_b/FTM0_CH5/LPUART0_CTS_b/JTAG_TCLK/SWD_CLK/EZP_CLK}
  - {pin_num: '53', peripheral: JTAG, signal: JTAG_TMS_SWD_DIO, pin_signal: TSI0_CH4/PTA3/UART0_RTS_b/FTM0_CH0/LPUART0_RTS_b/JTAG_TMS/SWD_DIO}
  - {pin_num: '61', peripheral: GPIOA, signal: 'GPIO, 9', pin_signal: PTA9/FTM1_CH1/MII0_RXD3/FTM1_QD_PHB/TPM1_CH1/TRACE_D1}
  - {pin_num: '63', peripheral: GPIOA, signal: 'GPIO, 11', pin_signal: PTA11/LLWU_P23/FTM2_CH1/MII0_RXCLK/I2C2_SDA/FTM2_QD_PHB/TPM2_CH1}
  - {pin_num: '65', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/RMII0_RXD0/MII0_RXD0/I2C2_SDA/I2S0_TX_FS/FTM1_QD_PHB/TPM1_CH1}
  - {pin_num: '67', peripheral: GPIOA, signal: 'GPIO, 15', pin_signal: CMP3_IN1/PTA15/SPI0_SCK/UART0_RX/RMII0_TXEN/MII0_TXEN/I2S0_RXD0}
  - {pin_num: '81', peripheral: FTM1, signal: 'QD_PH, A', pin_signal: ADC0_SE8/ADC1_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/SDRAM_CAS_b/FTM1_QD_PHA/TPM1_CH0}
  - {pin_num: '82', peripheral: FTM1, signal: 'QD_PH, B', pin_signal: ADC0_SE9/ADC1_SE9/TSI0_CH6/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/SDRAM_RAS_b/FTM1_QD_PHB/TPM1_CH1}
  - {pin_num: '97', peripheral: FTM2, signal: 'QD_PH, A', pin_signal: TSI0_CH11/PTB18/CAN0_TX/FTM2_CH0/I2S0_TX_BCLK/FB_AD15/SDRAM_A23/FTM2_QD_PHA/TPM2_CH0}
  - {pin_num: '98', peripheral: FTM2, signal: 'QD_PH, B', pin_signal: TSI0_CH12/PTB19/CAN0_RX/FTM2_CH1/I2S0_TX_FS/FB_OE_b/FTM2_QD_PHB/TPM2_CH1}
  - {pin_num: '111', peripheral: GPIOC, signal: 'GPIO, 6', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB0_EXTRG/I2S0_RX_BCLK/FB_AD9/SDRAM_A17/I2S0_MCLK}
  - {pin_num: '113', peripheral: GPIOC, signal: 'GPIO, 8', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7/SDRAM_A15}
  - {pin_num: '114', peripheral: GPIOC, signal: 'GPIO, 9', pin_signal: ADC1_SE5b/CMP0_IN3/PTC9/FTM3_CH5/I2S0_RX_BCLK/FB_AD6/SDRAM_A14/FTM2_FLT0}
  - {pin_num: '115', peripheral: GPIOC, signal: 'GPIO, 10', pin_signal: ADC1_SE6b/PTC10/I2C1_SCL/FTM3_CH6/I2S0_RX_FS/FB_AD5/SDRAM_A13}
  - {pin_num: '116', peripheral: GPIOC, signal: 'GPIO, 11', pin_signal: ADC1_SE7b/PTC11/LLWU_P11/I2C1_SDA/FTM3_CH7/I2S0_RXD1/FB_RW_b}
  - {pin_num: '117', peripheral: GPIOC, signal: 'GPIO, 12', pin_signal: PTC12/UART4_RTS_b/FTM_CLKIN0/FB_AD27/SDRAM_D27/FTM3_FLT0/TPM_CLKIN0}
  - {pin_num: '118', peripheral: GPIOC, signal: 'GPIO, 13', pin_signal: PTC13/UART4_CTS_b/FTM_CLKIN1/FB_AD26/SDRAM_D26/TPM_CLKIN1}
  - {pin_num: '119', peripheral: GPIOC, signal: 'GPIO, 14', pin_signal: PTC14/UART4_RX/FB_AD25/SDRAM_D25}
  - {pin_num: '120', peripheral: GPIOC, signal: 'GPIO, 15', pin_signal: PTC15/UART4_TX/FB_AD24/SDRAM_D24}
  - {pin_num: '125', peripheral: GPIOC, signal: 'GPIO, 18', pin_signal: PTC18/UART3_RTS_b/ENET0_1588_TMR2/FB_TBST_b/FB_CS2_b/FB_BE15_8_BLS23_16_b/SDRAM_DQM1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_Digital
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_Digital(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    /* PORTA0 (pin 50) is configured as JTAG_TCLK */
    PORT_SetPinMux(RTEPIN_DIGITAL_SWO_CLK_PORT, RTEPIN_DIGITAL_SWO_CLK_PIN, kPORT_MuxAlt7);

    /* PORTA11 (pin 63) is configured as PTA11 */
    PORT_SetPinMux(RTEPIN_DIGITAL_SWITCH_1_PORT, RTEPIN_DIGITAL_SWITCH_1_PIN, kPORT_MuxAsGpio);

    /* PORTA13 (pin 65) is configured as PTA13 */
    PORT_SetPinMux(RTEPIN_DIGITAL_SWITCH_2_PORT, RTEPIN_DIGITAL_SWITCH_2_PIN, kPORT_MuxAsGpio);

    /* PORTA15 (pin 67) is configured as PTA15 */
    PORT_SetPinMux(RTEPIN_DIGITAL_SWITCH_3_PORT, RTEPIN_DIGITAL_SWITCH_3_PIN, kPORT_MuxAsGpio);

    /* PORTA3 (pin 53) is configured as JTAG_TMS */
    PORT_SetPinMux(RTEPIN_DIGITAL_SWO_DIO_PORT, RTEPIN_DIGITAL_SWO_DIO_PIN, kPORT_MuxAlt7);

    /* PORTA9 (pin 61) is configured as PTA9 */
    PORT_SetPinMux(RTEPIN_DIGITAL_SWITCH_0_PORT, RTEPIN_DIGITAL_SWITCH_0_PIN, kPORT_MuxAsGpio);

    /* PORTB0 (pin 81) is configured as FTM1_QD_PHA */
    PORT_SetPinMux(RTEPIN_DIGITAL_ENCO_LA_PORT, RTEPIN_DIGITAL_ENCO_LA_PIN, kPORT_MuxAlt6);

    /* PORTB1 (pin 82) is configured as FTM1_QD_PHB */
    PORT_SetPinMux(RTEPIN_DIGITAL_ENCO_LB_PORT, RTEPIN_DIGITAL_ENCO_LB_PIN, kPORT_MuxAlt6);

    /* PORTB18 (pin 97) is configured as FTM2_QD_PHA */
    PORT_SetPinMux(RTEPIN_DIGITAL_ENCO_RA_PORT, RTEPIN_DIGITAL_ENCO_RA_PIN, kPORT_MuxAlt6);

    /* PORTB19 (pin 98) is configured as FTM2_QD_PHB */
    PORT_SetPinMux(RTEPIN_DIGITAL_ENCO_RB_PORT, RTEPIN_DIGITAL_ENCO_RB_PIN, kPORT_MuxAlt6);

    /* PORTC10 (pin 115) is configured as PTC10 */
    PORT_SetPinMux(RTEPIN_DIGITAL_CAM_D_2_PORT, RTEPIN_DIGITAL_CAM_D_2_PIN, kPORT_MuxAsGpio);

    /* PORTC11 (pin 116) is configured as PTC11 */
    PORT_SetPinMux(RTEPIN_DIGITAL_CAM_D_3_PORT, RTEPIN_DIGITAL_CAM_D_3_PIN, kPORT_MuxAsGpio);

    /* PORTC12 (pin 117) is configured as PTC12 */
    PORT_SetPinMux(RTEPIN_DIGITAL_CAM_D_4_PORT, RTEPIN_DIGITAL_CAM_D_4_PIN, kPORT_MuxAsGpio);

    /* PORTC13 (pin 118) is configured as PTC13 */
    PORT_SetPinMux(RTEPIN_DIGITAL_CAM_D_5_PORT, RTEPIN_DIGITAL_CAM_D_5_PIN, kPORT_MuxAsGpio);

    /* PORTC14 (pin 119) is configured as PTC14 */
    PORT_SetPinMux(RTEPIN_DIGITAL_CAM_D_6_PORT, RTEPIN_DIGITAL_CAM_D_6_PIN, kPORT_MuxAsGpio);

    /* PORTC15 (pin 120) is configured as PTC15 */
    PORT_SetPinMux(RTEPIN_DIGITAL_CAM_D_7_PORT, RTEPIN_DIGITAL_CAM_D_7_PIN, kPORT_MuxAsGpio);

    /* PORTC18 (pin 125) is configured as PTC18 */
    PORT_SetPinMux(RTEPIN_DIGITAL_CAM_PCLK_PORT, RTEPIN_DIGITAL_CAM_PCLK_PIN, kPORT_MuxAsGpio);

    /* PORTC6 (pin 111) is configured as PTC6 */
    PORT_SetPinMux(RTEPIN_DIGITAL_CAM_VSNC_PORT, RTEPIN_DIGITAL_CAM_VSNC_PIN, kPORT_MuxAsGpio);

    /* PORTC8 (pin 113) is configured as PTC8 */
    PORT_SetPinMux(RTEPIN_DIGITAL_CAM_D_0_PORT, RTEPIN_DIGITAL_CAM_D_0_PIN, kPORT_MuxAsGpio);

    /* PORTC9 (pin 114) is configured as PTC9 */
    PORT_SetPinMux(RTEPIN_DIGITAL_CAM_D_1_PORT, RTEPIN_DIGITAL_CAM_D_1_PIN, kPORT_MuxAsGpio);

    /* PORTE0 (pin 1) is configured as SDHC0_D1 */
    PORT_SetPinMux(RTEPIN_DIGITAL_SD_D_1_PORT, RTEPIN_DIGITAL_SD_D_1_PIN, kPORT_MuxAlt4);

    /* PORTE1 (pin 2) is configured as SDHC0_D0 */
    PORT_SetPinMux(RTEPIN_DIGITAL_SD_D_0_PORT, RTEPIN_DIGITAL_SD_D_0_PIN, kPORT_MuxAlt4);

    /* PORTE10 (pin 13) is configured as PTE10 */
    PORT_SetPinMux(RTEPIN_DIGITAL_BUTTON_OK_PORT, RTEPIN_DIGITAL_BUTTON_OK_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[10] = ((PORTE->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp)

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTE11 (pin 14) is configured as PTE11 */
    PORT_SetPinMux(RTEPIN_DIGITAL_BUTTON_DN_PORT, RTEPIN_DIGITAL_BUTTON_DN_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[11] = ((PORTE->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp)

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTE12 (pin 15) is configured as FTM3_CH7 */
    PORT_SetPinMux(RTEPIN_DIGITAL_SERVO_0_PORT, RTEPIN_DIGITAL_SERVO_0_PIN, kPORT_MuxAlt6);

    /* PORTE2 (pin 3) is configured as SDHC0_DCLK */
    PORT_SetPinMux(RTEPIN_DIGITAL_SD_CLK_PORT, RTEPIN_DIGITAL_SD_CLK_PIN, kPORT_MuxAlt4);

    /* PORTE3 (pin 4) is configured as SDHC0_CMD */
    PORT_SetPinMux(RTEPIN_DIGITAL_SD_CMD_PORT, RTEPIN_DIGITAL_SD_CMD_PIN, kPORT_MuxAlt4);

    /* PORTE4 (pin 7) is configured as SDHC0_D3 */
    PORT_SetPinMux(RTEPIN_DIGITAL_SD_D_3_PORT, RTEPIN_DIGITAL_SD_D_3_PIN, kPORT_MuxAlt4);

    /* PORTE5 (pin 8) is configured as SDHC0_D2 */
    PORT_SetPinMux(RTEPIN_DIGITAL_SD_D_2_PORT, RTEPIN_DIGITAL_SD_D_2_PIN, kPORT_MuxAlt4);

    /* PORTE7 (pin 10) is configured as PTE7 */
    PORT_SetPinMux(RTEPIN_DIGITAL_BUTTON_UP_PORT, RTEPIN_DIGITAL_BUTTON_UP_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[7] = ((PORTE->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp)

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTE8 (pin 11) is configured as PTE8 */
    PORT_SetPinMux(RTEPIN_DIGITAL_BUTTON_LF_PORT, RTEPIN_DIGITAL_BUTTON_LF_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[8] = ((PORTE->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp)

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTE9 (pin 12) is configured as PTE9 */
    PORT_SetPinMux(RTEPIN_DIGITAL_BUTTON_RT_PORT, RTEPIN_DIGITAL_BUTTON_RT_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[9] = ((PORTE->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp)

                     /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_ODE(kPORT_OpenDrainEnable));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_Analog:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '36', peripheral: ADC0, signal: 'SE, 16', pin_signal: ADC0_SE16/CMP1_IN2/ADC0_SE21}
  - {pin_num: '38', peripheral: ADC0, signal: 'SE, 23', pin_signal: DAC0_OUT/CMP1_IN3/ADC0_SE23}
  - {pin_num: '45', peripheral: ADC0, signal: 'SE, 17', pin_signal: ADC0_SE17/PTE24/CAN1_TX/UART4_TX/I2C0_SCL/EWM_OUT_b}
  - {pin_num: '46', peripheral: ADC0, signal: 'SE, 18', pin_signal: ADC0_SE18/PTE25/LLWU_P21/CAN1_RX/UART4_RX/I2C0_SDA/EWM_IN}
  - {pin_num: '59', peripheral: ADC0, signal: 'SE, 10', pin_signal: ADC0_SE10/PTA7/FTM0_CH4/RMII0_MDIO/MII0_MDIO/TRACE_D3}
  - {pin_num: '60', peripheral: ADC0, signal: 'SE, 11', pin_signal: ADC0_SE11/PTA8/FTM1_CH0/RMII0_MDC/MII0_MDC/FTM1_QD_PHA/TPM1_CH0/TRACE_D2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_Analog
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_Analog(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    /* PORTA7 (pin 59) is configured as ADC0_SE10 */
    PORT_SetPinMux(PORTA, 7U, kPORT_PinDisabledOrAnalog);

    /* PORTA8 (pin 60) is configured as ADC0_SE11 */
    PORT_SetPinMux(PORTA, 8U, kPORT_PinDisabledOrAnalog);

    /* PORTE24 (pin 45) is configured as ADC0_SE17 */
    PORT_SetPinMux(PORTE, 24U, kPORT_PinDisabledOrAnalog);

    /* PORTE25 (pin 46) is configured as ADC0_SE18 */
    PORT_SetPinMux(PORTE, 25U, kPORT_PinDisabledOrAnalog);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_UART0_DBG:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '51', peripheral: LPUART0, signal: RX, pin_signal: TSI0_CH2/PTA1/UART0_RX/FTM0_CH6/I2C3_SDA/LPUART0_RX/JTAG_TDI/EZP_DI}
  - {pin_num: '52', peripheral: LPUART0, signal: TX, pin_signal: TSI0_CH3/PTA2/UART0_TX/FTM0_CH7/I2C3_SCL/LPUART0_TX/JTAG_TDO/TRACE_SWO/EZP_DO}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_UART0_DBG
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_UART0_DBG(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);

    /* PORTA1 (pin 51) is configured as LPUART0_RX */
    PORT_SetPinMux(RTEPIN_UART0_DBG_UART_DBG_RX_PORT, RTEPIN_UART0_DBG_UART_DBG_RX_PIN, kPORT_MuxAlt5);

    /* PORTA2 (pin 52) is configured as LPUART0_TX */
    PORT_SetPinMux(RTEPIN_UART0_DBG_UART_DBG_TX_PORT, RTEPIN_UART0_DBG_UART_DBG_TX_PIN, kPORT_MuxAlt5);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_LPUART0TXSRC_MASK)))

                  /* LPUART0 transmit data source select: LPUART0_TX pin. */
                  | SIM_SOPT5_LPUART0TXSRC(SOPT5_LPUART0TXSRC_LPUART_TX));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_UART0_WLAN:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '133', peripheral: UART0, signal: RX, pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FB_AD0/FTM0_FLT0/SPI1_SOUT}
  - {pin_num: '136', peripheral: UART0, signal: TX, pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/SDRAM_CKE/FTM0_FLT1/SPI1_SIN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_UART0_WLAN
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_UART0_WLAN(void)
{
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

    /* PORTD6 (pin 133) is configured as UART0_RX */
    PORT_SetPinMux(RTEPIN_UART0_WLAN_UART_WLAN_RX_PORT, RTEPIN_UART0_WLAN_UART_WLAN_RX_PIN, kPORT_MuxAlt3);

    /* PORTD7 (pin 136) is configured as UART0_TX */
    PORT_SetPinMux(RTEPIN_UART0_WLAN_UART_WLAN_TX_PORT, RTEPIN_UART0_WLAN_UART_WLAN_TX_PIN, kPORT_MuxAlt3);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK)))

                  /* UART 0 transmit data source select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
