/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RTEPIN_BasicPin(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTA1 (number 51), UART0_SWO_RX
  @{ */
#define RTEPIN_UART0_SWO_UART0_SWO_RX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define RTEPIN_UART0_SWO_UART0_SWO_RX_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                                 /* @} */

/*! @name PORTA2 (number 52), UART0_SWO_TX
  @{ */
#define RTEPIN_UART0_SWO_UART0_SWO_TX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define RTEPIN_UART0_SWO_UART0_SWO_TX_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RTEPIN_Uart0_SWO(void);

/*! @name PORTD12 (number 141), OLED_1
  @{ */
#define RTEPIN_BOARD_OLED_1_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define RTEPIN_BOARD_OLED_1_PORT PORTD /*!<@brief PORT device name: PORTD */
#define RTEPIN_BOARD_OLED_1_PIN 12U    /*!<@brief PORTD pin index: 12 */
                                       /* @} */

/*! @name PORTD13 (number 142), OLED_3
  @{ */
#define RTEPIN_BOARD_OLED_3_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define RTEPIN_BOARD_OLED_3_PORT PORTD /*!<@brief PORT device name: PORTD */
#define RTEPIN_BOARD_OLED_3_PIN 13U    /*!<@brief PORTD pin index: 13 */
                                       /* @} */

/*! @name PORTD14 (number 143), OLED_2
  @{ */
#define RTEPIN_BOARD_OLED_2_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define RTEPIN_BOARD_OLED_2_PORT PORTD /*!<@brief PORT device name: PORTD */
#define RTEPIN_BOARD_OLED_2_PIN 14U    /*!<@brief PORTD pin index: 14 */
                                       /* @} */

/*! @name PORTD15 (number 144), OLED_4
  @{ */
#define RTEPIN_BOARD_OLED_4_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define RTEPIN_BOARD_OLED_4_PORT PORTD /*!<@brief PORT device name: PORTD */
#define RTEPIN_BOARD_OLED_4_PIN 15U    /*!<@brief PORTD pin index: 15 */
                                       /* @} */

/*! @name PORTD8 (number 137), IMU_SCL
  @{ */
#define RTEPIN_BOARD_IMU_SCL_PORT PORTD /*!<@brief PORT device name: PORTD */
#define RTEPIN_BOARD_IMU_SCL_PIN 8U     /*!<@brief PORTD pin index: 8 */
                                        /* @} */

/*! @name PORTD9 (number 138), IMU_SDA
  @{ */
#define RTEPIN_BOARD_IMU_SDA_PORT PORTD /*!<@brief PORT device name: PORTD */
#define RTEPIN_BOARD_IMU_SDA_PIN 9U     /*!<@brief PORTD pin index: 9 */
                                        /* @} */

/*! @name PORTE11 (number 14), SERVO_1
  @{ */
#define RTEPIN_BOARD_SERVO_1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define RTEPIN_BOARD_SERVO_1_PIN 11U    /*!<@brief PORTE pin index: 11 */
                                        /* @} */

/*! @name PORTE12 (number 15), SERVO_2
  @{ */
#define RTEPIN_BOARD_SERVO_2_PORT PORTE /*!<@brief PORT device name: PORTE */
#define RTEPIN_BOARD_SERVO_2_PIN 12U    /*!<@brief PORTE pin index: 12 */
                                        /* @} */

/*! @name PORTE6 (number 9), BUTTON_DN
  @{ */
#define RTEPIN_BOARD_BUTTON_DN_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define RTEPIN_BOARD_BUTTON_DN_PORT PORTE /*!<@brief PORT device name: PORTE */
#define RTEPIN_BOARD_BUTTON_DN_PIN 6U     /*!<@brief PORTE pin index: 6 */
                                          /* @} */

/*! @name PORTE7 (number 10), BUTTON_RT
  @{ */
#define RTEPIN_BOARD_BUTTON_RT_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define RTEPIN_BOARD_BUTTON_RT_PORT PORTE /*!<@brief PORT device name: PORTE */
#define RTEPIN_BOARD_BUTTON_RT_PIN 7U     /*!<@brief PORTE pin index: 7 */
                                          /* @} */

/*! @name PORTE8 (number 11), BUTTON_OK
  @{ */
#define RTEPIN_BOARD_BUTTON_OK_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define RTEPIN_BOARD_BUTTON_OK_PORT PORTE /*!<@brief PORT device name: PORTE */
#define RTEPIN_BOARD_BUTTON_OK_PIN 8U     /*!<@brief PORTE pin index: 8 */
                                          /* @} */

/*! @name PORTE9 (number 12), BUTTON_UP
  @{ */
#define RTEPIN_BOARD_BUTTON_UP_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define RTEPIN_BOARD_BUTTON_UP_PORT PORTE /*!<@brief PORT device name: PORTE */
#define RTEPIN_BOARD_BUTTON_UP_PIN 9U     /*!<@brief PORTE pin index: 9 */
                                          /* @} */

/*! @name PORTE10 (number 13), BUTTON_LF
  @{ */
#define RTEPIN_BOARD_BUTTON_LF_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define RTEPIN_BOARD_BUTTON_LF_PORT PORTE /*!<@brief PORT device name: PORTE */
#define RTEPIN_BOARD_BUTTON_LF_PIN 10U    /*!<@brief PORTE pin index: 10 */
                                          /* @} */

/*! @name ADC0_SE16 (number 36), MAG_0
  @{ */
/* @} */

/*! @name ADC0_SE23 (number 38), MAG_1
  @{ */
/* @} */

/*! @name PORTE24 (number 45), MAG_2
  @{ */
#define RTEPIN_BOARD_MAG_2_PORT PORTE /*!<@brief PORT device name: PORTE */
#define RTEPIN_BOARD_MAG_2_PIN 24U    /*!<@brief PORTE pin index: 24 */
                                      /* @} */

/*! @name PORTE25 (number 46), MAG_3
  @{ */
#define RTEPIN_BOARD_MAG_3_PORT PORTE /*!<@brief PORT device name: PORTE */
#define RTEPIN_BOARD_MAG_3_PIN 25U    /*!<@brief PORTE pin index: 25 */
                                      /* @} */

/*! @name PORTA7 (number 59), MAG_4
  @{ */
#define RTEPIN_BOARD_MAG_4_PORT PORTA /*!<@brief PORT device name: PORTA */
#define RTEPIN_BOARD_MAG_4_PIN 7U     /*!<@brief PORTA pin index: 7 */
                                      /* @} */

/*! @name PORTA8 (number 60), MAG_5
  @{ */
#define RTEPIN_BOARD_MAG_5_PORT PORTA /*!<@brief PORT device name: PORTA */
#define RTEPIN_BOARD_MAG_5_PIN 8U     /*!<@brief PORTA pin index: 8 */
                                      /* @} */

/*! @name PORTA12 (number 64), SWITCH_1
  @{ */
#define RTEPIN_BOARD_SWITCH_1_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define RTEPIN_BOARD_SWITCH_1_PORT PORTA /*!<@brief PORT device name: PORTA */
#define RTEPIN_BOARD_SWITCH_1_PIN 12U    /*!<@brief PORTA pin index: 12 */
                                         /* @} */

/*! @name PORTA14 (number 66), SWITCH_2
  @{ */
#define RTEPIN_BOARD_SWITCH_2_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define RTEPIN_BOARD_SWITCH_2_PORT PORTA /*!<@brief PORT device name: PORTA */
#define RTEPIN_BOARD_SWITCH_2_PIN 14U    /*!<@brief PORTA pin index: 14 */
                                         /* @} */

/*! @name PORTA16 (number 68), SWITCH_3
  @{ */
#define RTEPIN_BOARD_SWITCH_3_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define RTEPIN_BOARD_SWITCH_3_PORT PORTA /*!<@brief PORT device name: PORTA */
#define RTEPIN_BOARD_SWITCH_3_PIN 16U    /*!<@brief PORTA pin index: 16 */
                                         /* @} */

/*! @name PORTA19 (number 73), SWITCH_4
  @{ */
#define RTEPIN_BOARD_SWITCH_4_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define RTEPIN_BOARD_SWITCH_4_PORT PORTA /*!<@brief PORT device name: PORTA */
#define RTEPIN_BOARD_SWITCH_4_PIN 19U    /*!<@brief PORTA pin index: 19 */
                                         /* @} */

/*! @name PORTB0 (number 81), ENC_LA
  @{ */
#define RTEPIN_BOARD_ENC_LA_PORT PORTB /*!<@brief PORT device name: PORTB */
#define RTEPIN_BOARD_ENC_LA_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                       /* @} */

/*! @name PORTB1 (number 82), ENC_LB
  @{ */
#define RTEPIN_BOARD_ENC_LB_PORT PORTB /*!<@brief PORT device name: PORTB */
#define RTEPIN_BOARD_ENC_LB_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                       /* @} */

/*! @name PORTB18 (number 97), ENC_RA
  @{ */
#define RTEPIN_BOARD_ENC_RA_PORT PORTB /*!<@brief PORT device name: PORTB */
#define RTEPIN_BOARD_ENC_RA_PIN 18U    /*!<@brief PORTB pin index: 18 */
                                       /* @} */

/*! @name PORTB19 (number 98), ENC_RB
  @{ */
#define RTEPIN_BOARD_ENC_RB_PORT PORTB /*!<@brief PORT device name: PORTB */
#define RTEPIN_BOARD_ENC_RB_PIN 19U    /*!<@brief PORTB pin index: 19 */
                                       /* @} */

/*! @name PORTC1 (number 104), MOTOR_LA
  @{ */
#define RTEPIN_BOARD_MOTOR_LA_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_MOTOR_LA_PIN 1U     /*!<@brief PORTC pin index: 1 */
                                         /* @} */

/*! @name PORTC2 (number 105), MOTOR_LB
  @{ */
#define RTEPIN_BOARD_MOTOR_LB_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_MOTOR_LB_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                         /* @} */

/*! @name PORTC3 (number 106), MOTOR_RA
  @{ */
#define RTEPIN_BOARD_MOTOR_RA_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_MOTOR_RA_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                         /* @} */

/*! @name PORTC4 (number 109), MOTOR_RB
  @{ */
#define RTEPIN_BOARD_MOTOR_RB_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_MOTOR_RB_PIN 4U     /*!<@brief PORTC pin index: 4 */
                                         /* @} */

/*! @name PORTC6 (number 111), CAM_VSNC
  @{ */
#define RTEPIN_BOARD_CAM_VSNC_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define RTEPIN_BOARD_CAM_VSNC_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_CAM_VSNC_PIN 6U     /*!<@brief PORTC pin index: 6 */
                                         /* @} */

/*! @name PORTC8 (number 113), CAM_D0
  @{ */
#define RTEPIN_BOARD_CAM_D0_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define RTEPIN_BOARD_CAM_D0_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_CAM_D0_PIN 8U     /*!<@brief PORTC pin index: 8 */
                                       /* @} */

/*! @name PORTC9 (number 114), CAM_D1
  @{ */
#define RTEPIN_BOARD_CAM_D1_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define RTEPIN_BOARD_CAM_D1_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_CAM_D1_PIN 9U     /*!<@brief PORTC pin index: 9 */
                                       /* @} */

/*! @name PORTC10 (number 115), CAM_D2
  @{ */
#define RTEPIN_BOARD_CAM_D2_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define RTEPIN_BOARD_CAM_D2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_CAM_D2_PIN 10U    /*!<@brief PORTC pin index: 10 */
                                       /* @} */

/*! @name PORTC11 (number 116), CAM_D3
  @{ */
#define RTEPIN_BOARD_CAM_D3_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define RTEPIN_BOARD_CAM_D3_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_CAM_D3_PIN 11U    /*!<@brief PORTC pin index: 11 */
                                       /* @} */

/*! @name PORTC12 (number 117), CAM_D4
  @{ */
#define RTEPIN_BOARD_CAM_D4_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define RTEPIN_BOARD_CAM_D4_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_CAM_D4_PIN 12U    /*!<@brief PORTC pin index: 12 */
                                       /* @} */

/*! @name PORTC13 (number 118), CAM_D5
  @{ */
#define RTEPIN_BOARD_CAM_D5_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define RTEPIN_BOARD_CAM_D5_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_CAM_D5_PIN 13U    /*!<@brief PORTC pin index: 13 */
                                       /* @} */

/*! @name PORTC14 (number 119), CAM_D6
  @{ */
#define RTEPIN_BOARD_CAM_D6_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define RTEPIN_BOARD_CAM_D6_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_CAM_D6_PIN 14U    /*!<@brief PORTC pin index: 14 */
                                       /* @} */

/*! @name PORTC15 (number 120), CAM_D7
  @{ */
#define RTEPIN_BOARD_CAM_D7_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define RTEPIN_BOARD_CAM_D7_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_CAM_D7_PIN 15U    /*!<@brief PORTC pin index: 15 */
                                       /* @} */

/*! @name PORTC16 (number 123), CAM_RX
  @{ */
#define RTEPIN_BOARD_CAM_RX_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_CAM_RX_PIN 16U    /*!<@brief PORTC pin index: 16 */
                                       /* @} */

/*! @name PORTC17 (number 124), CAM_TX
  @{ */
#define RTEPIN_BOARD_CAM_TX_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_CAM_TX_PIN 17U    /*!<@brief PORTC pin index: 17 */
                                       /* @} */

/*! @name PORTC18 (number 125), CAM_PCLK
  @{ */
#define RTEPIN_BOARD_CAM_PCLK_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define RTEPIN_BOARD_CAM_PCLK_PORT PORTC /*!<@brief PORT device name: PORTC */
#define RTEPIN_BOARD_CAM_PCLK_PIN 18U    /*!<@brief PORTC pin index: 18 */
                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RTEPIN_Board(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTD6 (number 133), UART0_SPP_RX
  @{ */
#define RTEPIN_UART0_SPP_UART0_SPP_RX_PORT PORTD /*!<@brief PORT device name: PORTD */
#define RTEPIN_UART0_SPP_UART0_SPP_RX_PIN 6U     /*!<@brief PORTD pin index: 6 */
                                                 /* @} */

/*! @name PORTD7 (number 136), UART0_SPP_TX
  @{ */
#define RTEPIN_UART0_SPP_UART0_SPP_TX_PORT PORTD /*!<@brief PORT device name: PORTD */
#define RTEPIN_UART0_SPP_UART0_SPP_TX_PIN 7U     /*!<@brief PORTD pin index: 7 */
                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RTEPIN_Uart0_SPP(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
